### ISSUE TITLE
Integrated dev tooling for service

### ISSUE THREAD

**Issue by qtrfeast** [pedestal/pedestal#168]
#92 introduced a number of helpful changes to the generated project.clj and REPL workflow on an app project. We should provide similar interface and ease-of-use in generated service applications as app-template does.

**Tasks**
- [x] Generated [dev.clj](../blob/master/service-template/src/leiningen/new/pedestal_service/dev.clj) should be `io.pedestal.service.dev` (or some other ns in the service library)
- [x] Generated [project.clj](../blob/master/service-template/src/leiningen/new/pedestal_service/project.clj) should...
  - [x] Automatically load `io.pedestal.service.dev` (but never fail, see 99a6ad6a300c8f714c0e802b399567aacb51a5f2)
  - [x] Print a useful introduction message
  - [x] Start in `user` namespace (may need to place dummy `user.clj` file in generated project.)
- [x] CHANGELOG.md should be updated with upgrade instructions similar to app's upgrade instructions.
- [x] lein run should still work
- [x] lein repl and `(start)` should still work
- [x] lein run-dev should still work
- [x] Generated uberjar should work with Beanstalk (is this exercising the servlet code?)
- [x] Consider adding tools-help and REPL-launch notice so we don't have to upgrade this in the future.
